# Prod Environment Values
images:
  repository: us-central1-docker.pkg.dev/ai-for-sre-demo/microservices-demo
adService:
  tag: "b610829"
cartService:
  tag: "748bb04"
checkoutService:
  tag: "748bb04"
currencyService:
  tag: "748bb04"
emailService:
  tag: "b610829"
frontend:
  tag: "caf505e"
loadGenerator:
  tag: "b610829"
paymentService:
  tag: "748bb04"
productCatalogService:
  tag: "4dc6cab"
recommendationService:
  tag: "b610829"
shippingService:
  tag: "748bb04"
